### PR TITLE
Use Jekyll Seo-tags Plugin for Search Engine and Social Media Searches

### PR DESCRIPTION
**Pull request by njsch**
I can see what you mean from your FB reply about Jekyll being new to you. Out of curiosity, did you initially invoke `jekyll new` or `jekyll build` from a terminal/console to create the main website template? Because you don't have a very detailed _config and gem files.

I've mildly fixed this but you really need to work on catering for potential data and software version validation issues.

The main concern is: you don't have a means of reaching people in Google and Facebook searches. But since the 2022 Federal Election is only 10 days away and Google search indexing can take up to 6 weeks to catch up to what has been put up on the internet, you're probably already too late anyway. But here's a start.

### CODE REVIEW

**Comment by curiousdannii** [comment]
Github pages automatically loads jekyll-seo-tag so is it really necessary to specify it there?

The full list is:

```
         Requiring: jekyll-github-metadata
         Requiring: jekyll-seo-tag
         Requiring: jekyll-coffeescript
         Requiring: jekyll-commonmark-ghpages
         Requiring: jekyll-gist
         Requiring: jekyll-github-metadata
         Requiring: jekyll-paginate
         Requiring: jekyll-relative-links
         Requiring: jekyll-optional-front-matter
         Requiring: jekyll-readme-index
         Requiring: jekyll-default-layout
         Requiring: jekyll-titles-from-headings
```

**Comment by njsch** [comment]
@curiousdannii, I've never been quite sure. The Github-Pages instructions say to initially build the site locally so I've sometimes been confused about explicit vs implicit support for Jekyll extensions.

**Comment by njsch** [comment]
Should have checked the source output first. Looks like you're right.

**Comment by curiousdannii** [comment]
All good, I think I will add a description, though a slightly more informative one.

**Pull request closed without merging**
